
services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Thien@123456
      ACCEPT_EULA: Y
    ports:
      - "1444:1433"
    networks:
      - SC-mynetwork

  user-service:
    container_name: user-service
    build:
      context: ./
      dockerfile: UserPresentation\Dockerfile
    ports:
      - 3333:80
    networks :
      - SC-mynetwork
    environment:
      ASPNETCORE_ENVIRONMENT : Staging
    volumes:
      - '../UserService/UserPresentation:/app/data'
    depends_on:
      - db



  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - SC-mynetwork

  
networks:
  SC-mynetwork:
    driver : bridge
